apiVersion: v1
kind: Service
metadata:
  name: vue-svc
  labels: # service monitor 의 selector 를 위하여 생성
    app: vue
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: vue
