apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-app
        image: aksaz01devvvd01registry.azurecr.io/hurivono/joohan_springboot_crud_security:241028_01
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health  # liveness 체크 경로 (예시)
            port: 8080
          initialDelaySeconds: 30  # 처음 체크하기 전 대기 시간
          periodSeconds: 30  # 체크 간격
          timeoutSeconds: 5  # 응답 대기 시간
          failureThreshold: 3  # 실패 기준 횟수
        readinessProbe:
          httpGet:
            path: /actuator/health  # readiness 체크 경로 (예시)
            port: 8080
          initialDelaySeconds: 15  # 처음 체크하기 전 대기 시간
          periodSeconds: 30  # 체크 간격
          timeoutSeconds: 5  # 응답 대기 시간
          failureThreshold: 3  # 실패 기준 횟수
