apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels: # service monitor 의 selector 를 위하여 생성
    app: backend
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002
    name: http
  selector:
    app: backend
  type: NodePort
