apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: joohan
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: joohan
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: frontend
    repoURL: https://github.com/hurivono/joohan_fullstack_ops
    targetRevision: HEAD
